name: 🚀 Deploy Backend to VPS

on:
  push:
    branches: [ master ] # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "., !node_modules, !dist"
          target: "~/proven"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/proven/proven-backend
            echo "🚀 [Deploy] Stopping & Building..."
            docker compose -f docker-compose.prod.yml up -d --build backend
            echo "✅ [Deploy] Finished successfully."
